language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - "12"
before_script:
  - npm install ganache
install:
  - npm install
script:
  - ganache-cli &
  - npm run travis
after_script:
  - npm run clean