language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - "12"
before_script:
  - npm install ganache
  - ganache-cli -p 8545 > /dev/null &
  - sleep 5
install:
  - npm install
script:
  - npm run travis
after_script:
  - npm run clean