sudo: required
dist: trusty
language: node_js
node_js:
  - "10"
before_script:
  - ganache-cli > /dev/null &
install:
  - npm install
  - npm install ganache
script:
  - npm run travis
after_script:
  - npm run clean
